# Site settings
title:My home
email:chwong1996@gmail.com
description:> # this means to ignore newlines until "baseurl:"
"A space to collect thoughts... from me"
github_username:"chwong1996"

# Build settings
markdown: 

highlighter: rouge

#Pagination:
  paginate: 15
  paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: false
    permalink: /portfolio/:path/

