# Site settings
title: My home
email: "chwong1996@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  "A space to collect thoughts... from me"
baseurl: #ddyy
url:  # the base hostname & protocol for your site
github_username:  "chwong1996"

# Build settings
markdown: kramdown

highlighter: rouge

#Pagination:
  paginate: 15
  paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

