# Site settings
title:My home
email:chwong1996@gmail.com
description:"A space to collect thoughts... from me"
baseurl:#none
url:#none
github_username:"chwong1996"

# Build settings
markdown: kramdown

highlighter: rouge

#Pagination:
  paginate: 15
  paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

