# Site settings
title: My home
email: chwong1996@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A space to collect thoughts... from me
github_username:  chwong1996

# Build settings
markdown: kramdown

highlighter: rouge

gems: [jekyll-paginate]

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
    portfolio:
        output: true
        permalink: "/portfolio/:title"
        
 # Instagram plugin
instagram_cache:    false # or true
instagram_cache_dir:    '.instagram-cache'      # default '.instagram-cache'